[package]
name = "calmui"
version = "0.1.0"
edition = "2024"

[features]
extend-icon = []

[dependencies]
gpui = { git = "https://github.com/AldenClark/zed.git", package = "gpui", rev = "de37e4b11df532fa9b610a8bf34779c9ef0f8fb0" }
rust-embed = "8.5.0"
pulldown-cmark = "0.12"
rust_decimal = "1.36"

[target.'cfg(target_vendor = "apple")'.dependencies]
core-text = "=21.0.0"
